### PR TITLE
Make it work with Firefox

### PR DESCRIPTION
**Pull request by dufferzafar**
~~Also adds an icon.~~

### CODE REVIEW

**Review by jlfwong — CHANGES_REQUESTED** [review]
Thanks for the Firefox support and for contributing in general!

I think I'd prefer to either make our own icon or to leave it without one. I suspect that Facebook wouldn't be too happy with us using their icon :)

**Comment by dufferzafar** [comment]
There are a lot of messenger related addons / apps and almost all of them have this icon.

I for one would prefer this icon because that is what I associate messenger with. 

But yeah, IANAL, so am not sure what the right thing to do is tbh.

**Comment by jlfwong** [comment]
You're certainly free to use this icon in your own fork, but I'd prefer not to use assets not created by contributors to my projects.

**Comment by dufferzafar** [comment]
That seems fair. I've removed the icon from this pull. But will still keep it on my fork.

@jlfwong Do you mind if I push this extension onto Mozilla's Addon Store? (with the icon etc.)

**Comment by jlfwong** [comment]
Thanks! Can you add instructions to the README for how to install this in Firefox from source, just as the current instructions show how to install this in Chrome from source?

Feel free to publish to the Mozilla Addon Store w/ the icon, so long as it's clearly under your own name and not mine.

I haven't published this to the Chrome store, but I'd like to reserve the right to do that myself in the future.

I'll merge this after the README update.

**Comment by dufferzafar** [comment]
I've updated the readme with firefox instructions.

**Comment by jlfwong** [comment]
Thanks 😄

**Pull request merged**
